In [1]:
import viz
import numpy as np
import pandas as pd
np.random.seed(8675309)

# How likely is it that you roll doubles when rolling two dice?

In [2]:
#Simulation
#roll 2 dice 36 times

n_trials = nrows = 10000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[2, 5],
       [5, 1],
       [1, 2],
       ...,
       [1, 6],
       [3, 2],
       [4, 1]])

In [3]:
doubles = np.diff(rolls) == 0
doubles

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [4]:
doubles.mean()

0.1643

# If you flip 8 coins, what is the probability of getting exactly 3 heads?

In [5]:
n_trials = nrows = 10000
n_coins = ncols = 8

flips = np.random.choice([0, 1], n_trials * n_coins).reshape(nrows, ncols)
flips

array([[0, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 1],
       [1, 0, 1, ..., 1, 1, 1],
       ...,
       [1, 0, 1, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 1, 0, 1]])

In [6]:
exact = np.sum(flips, axis=1) == 3
exact

array([False, False, False, ..., False, False, False])

In [7]:
exact.mean()

0.2149

# More than 3 heads?

In [8]:
more = np.sum(flips, axis=1) > 3
more

array([False, False,  True, ...,  True,  True,  True])

In [9]:
more.mean()

0.6367

## There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [10]:
n_trials = nrows = 10000
n_bb = ncols = 2

dsbb = np.random.choice([0, 1, 2, 3], n_trials * n_bb).reshape(nrows, ncols)
dsbb

array([[0, 0],
       [2, 0],
       [3, 1],
       ...,
       [1, 1],
       [0, 3],
       [2, 3]])

In [11]:
ds = np.sum(dsbb, axis=1) == 6
ds

array([False, False, False, ..., False, False, False])

In [12]:
ds.mean()

0.0642

## Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [53]:
#17 start - 3 per day stdev 1.5. what on Friday?

n_trials = nrows = 10000
poptarts_selection = ncols = 5

tarts = np.random.normal(loc = 3, scale = 1.5, size = (nrows, ncols))
tarts

array([[ 2.94274992,  2.74473468,  1.09670821, -0.0400346 ,  3.67037175],
       [ 4.80827143,  4.06790203,  3.88785208,  1.16669008,  1.73465559],
       [-0.05179965,  3.46520877,  3.19183818,  2.90888527,  0.14625905],
       ...,
       [ 5.30012876,  1.16711276,  4.4273923 ,  3.66113699,  3.4223282 ],
       [ 2.35531748,  0.99221262,  5.24463581,  2.6403109 ,  5.83507304],
       [ 3.72994122,  8.78730662,  3.43187725,  3.18197376,  4.07561356]])

In [54]:
any_left = (np.sum(tarts, axis=1)) < 17
any_left

array([ True,  True,  True, ..., False, False, False])

In [55]:
any_left.mean()

0.7278

## Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.


If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [16]:
n_trials = nrows = 10000
n_fields = ncols = 1

men = np.random.normal(loc = 178, scale = 8, size = (nrows,))
women = np.random.normal(loc = 170, scale = 6, size = (nrows,))
men

array([173.77448671, 167.68622513, 179.90987647, ..., 188.87623866,
       178.81748483, 178.46725611])

In [17]:
d = {'men': men, 'women': women}
height = pd.DataFrame.from_dict(d)
height

men       women
0     173.774487  160.503771
1     167.686225  160.747284
2     179.909876  174.975923
3     184.089490  173.746130
4     179.028346  181.805379
...          ...         ...
9995  177.363348  166.217457
9996  178.314248  165.872822
9997  188.876239  172.848314
9998  178.817485  171.733424
9999  178.467256  171.301300

[10000 rows x 2 columns]

In [18]:
tall_gurl = height['women'] > height['men']
tall_gurl

0       False
1       False
2       False
3       False
4        True
        ...  
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [19]:
np.sum(tall_gurl) / len(height)

0.2067

## When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [20]:
n_trials = nrows = 10000
students = ncols = 50

corrupt = np.random.choice([0, 1], n_trials * students, p = [.996, .004]).reshape(nrows, ncols)
corrupt

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [21]:
errors = np.sum(corrupt, axis = 1) >= 1
1 - errors.mean()

0.8228

In [22]:
n_trials = nrows = 10000
students_100 = ncols = 100

corrupt_100 = np.random.choice([0, 1], n_trials * students_100, p = [.996, .004]).reshape(nrows, ncols)
corrupt_100

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
errors_100 = np.sum(corrupt_100, axis = 1) >= 1
1 - errors_100.mean()

0.6676

In [24]:
n_trials = nrows = 10000
students_150 = ncols = 150

corrupt_150 = np.random.choice([0, 1], n_trials * students_150, p = [.996, .004]).reshape(nrows, ncols)
corrupt_150

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [25]:
errors_150 = np.sum(corrupt_150, axis = 1) >= 1
errors_150.mean()

0.4539

## How likely is it that 450 students all download anaconda without an issue?

In [26]:
n_trials = nrows = 10000
students_450 = ncols = 450

corrupt_450 = np.random.choice([0, 1], n_trials * students_450, p = [.996, .004]).reshape(nrows, ncols)
corrupt_450

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [27]:
errors_450 = np.sum(corrupt_450, axis = 1) >= 1
1 - errors_450.mean()

0.16279999999999994

In [28]:
n_trials = nrows = 10000
students_1000 = ncols = 1000

corrupt_1000 = np.random.choice([0, 1], n_trials * students_1000, p = [.996, .004]).reshape(nrows, ncols)
corrupt_1000

errors_1000 = np.sum(corrupt_1000, axis = 1) >= 1
errors_1000.mean()

0.9814

## There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

In [29]:
n_trials = nrows = 10000
days = ncols = 3

trukz = np.random.choice([0, 1], n_trials * days, p = [.3, .7]).reshape(nrows, ncols)
trukz

yummy_time = np.sum(trukz, axis = 1) >= 1
1 - yummy_time.mean()

0.025399999999999978

In [57]:
n_trials = nrows = 10000
days_7 = ncols = 5

trukz_7 = np.random.choice([0, 1], n_trials * days_7, p = [.3, .7]).reshape(nrows, ncols)
trukz_7

yummy_time_7 = np.sum(trukz_7, axis = 1) >= 1
yummy_time_7.mean()

0.9978

## If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [31]:
n_trials = nrows = 10000
people = ncols = 23

bday = np.random.choice((range(1, 366, 1)), size = n_trials * people).reshape(nrows, ncols)
bday

array([[  1, 137, 364, ..., 196, 156,  21],
       [223,  66, 178, ..., 175,  92,  53],
       [358, 336, 212, ..., 265,  34, 328],
       ...,
       [296,  39, 181, ...,  81, 166, 101],
       [ 67,  97,  76, ..., 358,  75, 244],
       [258,  20, 246, ..., 213, 313, 284]])

In [97]:
bbday = pd.DataFrame(bday)

In [110]:
series = bbday.nunique(axis = 1)
series

0       23
1       23
2       21
3       23
4       22
        ..
9995    23
9996    21
9997    22
9998    23
9999    23
Length: 10000, dtype: int64

In [112]:
(series<23).mean()

0.5085